### ISSUE TITLE
what's the meaning of -_-

### ISSUE THREAD

**Issue by CFourPO** [nickpalenchar/yaon#11]
>  4.6 Empty. Automatically denotes an empty list, string, or object depending on context
> 
> \o/
> empty object | \o/ -_- \o/ $$=> {}
> empty list,,, -_-          $$=> []
> empty string | -_-         $$=> ""
> \o/

And also...you tend to use `$$=>` a lot as line comments toward the end... @nickpalenchar

**Comment by nickpalenchar** [comment]
read the docs
