### ISSUE TITLE
ERR_TOO_MANY_REDIRECTS 

### ISSUE THREAD

**Issue by CFourPO** [nickpalenchar/yaon#17]
![image](https://user-images.githubusercontent.com/7713603/31795309-4fb78f6e-b4f3-11e7-8848-6a9e9096b6ae.png)

**Comment by nickpalenchar** [comment]
You need to add www for now. Help me with DNS GitHub is dumb with it

**Comment by CFourPO** [comment]
[try this](https://help.github.com/articles/setting-up-an-apex-domain/)

**Comment by CFourPO** [comment]
I would love to assist you but its not something I have control over. You have to configure it with your DNS provider

**Comment by CFourPO** [comment]
Resolved by adding the following records to the DNS settings for yaon.org:
`A - nickpalenchar.github.io - 192.30.252.153 - Auto`
`A - nickpalenchar.github.io - 192.30.252.154 - Auto`
